#!/bin/bash
# Script to prepare firmware for Wokwi testing
# This creates a combined firmware image with bootloader, partitions, and app

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WOKWI_DIR="$PROJECT_ROOT/test/wokwi"

# Check if environment is specified
if [ -z "$1" ]; then
    echo "Usage: $0 <environment>"
    echo "Example: $0 esp32_V4_wokwi_debug"
    exit 1
fi

ENV_NAME=$1
BUILD_DIR="$PROJECT_ROOT/.pio/build/$ENV_NAME"
FIRMWARE_BIN="$BUILD_DIR/firmware.bin"
FIRMWARE_ELF="$BUILD_DIR/firmware.elf"

echo "=== Preparing firmware for Wokwi simulation ==="
echo "Environment: $ENV_NAME"
echo "Build directory: $BUILD_DIR"
echo ""

# Check if build directory exists
if [ ! -d "$BUILD_DIR" ]; then
    echo "❌ ERROR: Build directory not found: $BUILD_DIR"
    echo "Please build the firmware first: pio run -e $ENV_NAME"
    exit 1
fi

echo "Searching for required files in build directory..."
echo ""

# Function to find file with multiple possible locations
find_file() {
    local file_desc=$1
    shift
    local found_file=""
    
    echo "Looking for $file_desc:"
    for path in "$@"; do
        echo "  Checking: $path"
        if [ -f "$path" ]; then
            found_file="$path"
            echo "  ✓ Found at: $path"
            echo "$found_file"
            return 0
        fi
    done
    
    echo "  ❌ Not found in any expected location"
    return 1
}

# Find firmware.bin
FIRMWARE_BIN=$(find_file "firmware.bin" \
    "$BUILD_DIR/firmware.bin") || {
    echo ""
    echo "❌ ERROR: firmware.bin not found"
    FIRMWARE_BIN=""
}
echo ""

# Find bootloader.bin - check multiple common locations
BOOTLOADER_BIN=$(find_file "bootloader.bin" \
    "$BUILD_DIR/bootloader.bin" \
    "$BUILD_DIR/bootloader/bootloader.bin" \
    "$BUILD_DIR/esp-idf/bootloader/bootloader.bin") || {
    echo ""
    echo "❌ ERROR: bootloader.bin not found"
    echo "Searching entire build directory for bootloader.bin:"
    find "$BUILD_DIR" -name "bootloader.bin" -type f 2>/dev/null | while read f; do
        echo "  Found: $f"
    done
    BOOTLOADER_BIN=""
}
echo ""

# Find partitions.bin - check multiple common locations
PARTITIONS_BIN=$(find_file "partitions.bin" \
    "$BUILD_DIR/partitions.bin" \
    "$BUILD_DIR/partitions/partitions.bin") || {
    echo ""
    echo "❌ ERROR: partitions.bin not found"
    echo "Searching entire build directory for partitions.bin:"
    find "$BUILD_DIR" -name "partitions.bin" -type f 2>/dev/null | while read f; do
        echo "  Found: $f"
    done
    PARTITIONS_BIN=""
}
echo ""

# Check if any files are missing
MISSING_FILES=""
[ -z "$FIRMWARE_BIN" ] && MISSING_FILES="${MISSING_FILES}firmware.bin "
[ -z "$BOOTLOADER_BIN" ] && MISSING_FILES="${MISSING_FILES}bootloader.bin "
[ -z "$PARTITIONS_BIN" ] && MISSING_FILES="${MISSING_FILES}partitions.bin "

if [ -n "$MISSING_FILES" ]; then
    echo "❌ ERROR: Missing required files: $MISSING_FILES"
    echo ""
    echo "Build directory structure:"
    echo "----------------------------------------"
    ls -lR "$BUILD_DIR" | head -50
    echo "----------------------------------------"
    echo ""
    echo "These files are generated by PlatformIO/ESP-IDF during the build process."
    echo ""
    echo "Troubleshooting steps:"
    echo "1. Ensure the build completed successfully: pio run -e $ENV_NAME"
    echo "2. Check for build errors in PlatformIO output"
    echo "3. Verify partition table is specified in platformio.ini"
    echo "4. For ESP-IDF framework, bootloader should be auto-generated"
    echo ""
    echo "If files are in unexpected locations, the script will show them above."
    exit 1
fi

echo "✅ All required files found!"
echo ""

echo "Creating combined firmware image for Wokwi..."
echo "Using files from $ENV_NAME build:"
echo "  - Bootloader: $(basename $(dirname "$BOOTLOADER_BIN"))/$(basename "$BOOTLOADER_BIN")"
echo "  - Partitions: $PARTITIONS_BIN"
echo "  - Firmware:   $FIRMWARE_BIN"

# Create combined firmware image using esptool.py
# Standard ESP32 flash layout:
#   0x1000 - bootloader
#   0x8000 - partition table
#   0x10000 - application
echo ""
echo "Merging firmware components into combined image..."

# Check if esptool.py is available
if ! command -v esptool.py &> /dev/null; then
    echo "❌ ERROR: esptool.py not found"
    echo "Installing esptool..."
    pip install esptool || {
        echo "❌ ERROR: Failed to install esptool"
        echo "Please install manually: pip install esptool"
        exit 1
    }
fi

# Merge binaries into a single combined image
# This is the recommended approach for Wokwi to ensure proper filesystem support
esptool.py --chip esp32 merge_bin \
    -o "$WOKWI_DIR/firmware-combined.bin" \
    --flash_mode dio \
    --flash_freq 40m \
    --flash_size 4MB \
    0x1000 "$BOOTLOADER_BIN" \
    0x8000 "$PARTITIONS_BIN" \
    0x10000 "$FIRMWARE_BIN"

echo "✓ Created combined firmware image: firmware-combined.bin"

# Also copy ELF file for debugging
if [ -f "$FIRMWARE_ELF" ]; then
    cp "$FIRMWARE_ELF" "$WOKWI_DIR/firmware.elf"
    echo "✓ Copied firmware.elf for debugging"
else
    echo "⚠ Warning: firmware.elf not found"
fi

# Display combined image information
echo ""
echo "Combined firmware image details:"
ls -lh "$WOKWI_DIR/firmware-combined.bin"
echo ""
echo "Image structure:"
echo "  0x00001000 - Bootloader ($(stat -f%z "$BOOTLOADER_BIN" 2>/dev/null || stat -c%s "$BOOTLOADER_BIN") bytes)"
echo "  0x00008000 - Partition table ($(stat -f%z "$PARTITIONS_BIN" 2>/dev/null || stat -c%s "$PARTITIONS_BIN") bytes)"
echo "  0x00010000 - Application ($(stat -f%z "$FIRMWARE_BIN" 2>/dev/null || stat -c%s "$FIRMWARE_BIN") bytes)"

# Verify the combined image
echo ""
echo "Verifying combined image..."
python3 -c "
import sys
try:
    with open('$WOKWI_DIR/firmware-combined.bin', 'rb') as f:
        data = f.read()
    print(f'✓ Combined image size: {len(data)} bytes ({len(data)/1024/1024:.2f} MB)')
    
    # Check bootloader magic byte at offset 0x1000
    if len(data) > 0x1000 and data[0x1000] == 0xe9:
        print('✓ Bootloader magic byte (0xe9) found at 0x1000')
    else:
        print('⚠ Warning: Bootloader magic byte not found at expected location')
    
    # Check partition table magic bytes at offset 0x8000
    if len(data) > 0x8000 and data[0x8000:0x8002] == b'\xaa\x50':
        print('✓ Partition table magic bytes found at 0x8000')
    else:
        print('⚠ Warning: Partition table magic bytes not found at expected location')
    
    # Check application magic byte at offset 0x10000
    if len(data) > 0x10000 and data[0x10000] == 0xe9:
        print('✓ Application magic byte (0xe9) found at 0x10000')
    else:
        print('⚠ Warning: Application magic byte not found at expected location')
        
except Exception as e:
    print(f'❌ ERROR verifying image: {e}')
    sys.exit(1)
"

echo ""
echo "✅ Firmware prepared successfully!"
echo "Combined firmware image ready for Wokwi simulation."
