#!/bin/bash
# Script to prepare firmware for Wokwi testing
# This copies the built firmware to the test directory

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WOKWI_DIR="$PROJECT_ROOT/test/wokwi"

# Check if environment is specified
if [ -z "$1" ]; then
    echo "Usage: $0 <environment>"
    echo "Example: $0 esp32_V4_wokwi_debug"
    exit 1
fi

ENV_NAME=$1
BUILD_DIR="$PROJECT_ROOT/.pio/build/$ENV_NAME"
FIRMWARE_BIN="$BUILD_DIR/firmware.bin"
FIRMWARE_ELF="$BUILD_DIR/firmware.elf"

# PlatformIO stores bootloader and partitions in the build directory
# but they might be in subdirectories depending on the platform version
BOOTLOADER_BIN="$BUILD_DIR/bootloader.bin"
PARTITIONS_BIN="$BUILD_DIR/partitions.bin"

# Alternative locations for bootloader (ESP-IDF v4+ might use different paths)
if [ ! -f "$BOOTLOADER_BIN" ]; then
    ALT_BOOTLOADER="$BUILD_DIR/bootloader/bootloader.bin"
    if [ -f "$ALT_BOOTLOADER" ]; then
        BOOTLOADER_BIN="$ALT_BOOTLOADER"
    fi
fi

# Check if firmware exists
if [ ! -f "$FIRMWARE_BIN" ]; then
    echo "Error: Firmware binary not found at $FIRMWARE_BIN"
    echo "Please build the firmware first: pio run -e $ENV_NAME"
    exit 1
fi

# Copy firmware to test directory
echo "Copying firmware from $ENV_NAME to test directory..."
cp "$FIRMWARE_BIN" "$WOKWI_DIR/firmware.bin"
echo "✓ Copied firmware.bin"

if [ -f "$FIRMWARE_ELF" ]; then
    cp "$FIRMWARE_ELF" "$WOKWI_DIR/firmware.elf"
    echo "✓ Copied firmware.elf"
else
    echo "⚠ Warning: firmware.elf not found"
fi

# Copy bootloader and partitions (required for filesystem support)
MISSING_FILES=""

if [ -f "$BOOTLOADER_BIN" ]; then
    cp "$BOOTLOADER_BIN" "$WOKWI_DIR/bootloader.bin"
    echo "✓ Copied bootloader.bin from $(basename $(dirname "$BOOTLOADER_BIN"))/$(basename "$BOOTLOADER_BIN")"
else
    echo "❌ ERROR: bootloader.bin not found!"
    echo "   Checked: $BOOTLOADER_BIN"
    echo "   Also checked: $BUILD_DIR/bootloader/bootloader.bin"
    MISSING_FILES="${MISSING_FILES}bootloader.bin "
    # List build directory contents to help debug
    echo "   Build directory contents:"
    ls -la "$BUILD_DIR" | head -20
fi

if [ -f "$PARTITIONS_BIN" ]; then
    cp "$PARTITIONS_BIN" "$WOKWI_DIR/partitions.bin"
    echo "✓ Copied partitions.bin"
    # Display partition table contents for verification
    echo "   Partition table contents:"
    python3 -c "
import sys
try:
    with open('$WOKWI_DIR/partitions.bin', 'rb') as f:
        data = f.read()
    print(f'   Size: {len(data)} bytes')
    print(f'   First 32 bytes (hex): {data[:32].hex()}')
except Exception as e:
    print(f'   Could not read: {e}')
" || true
else
    echo "❌ ERROR: partitions.bin not found at $PARTITIONS_BIN"
    MISSING_FILES="${MISSING_FILES}partitions.bin "
    # List build directory contents to help debug
    echo "   Build directory contents:"
    ls -la "$BUILD_DIR" | head -20
fi

if [ -n "$MISSING_FILES" ]; then
    echo ""
    echo "❌ ERROR: Missing required files: $MISSING_FILES"
    echo ""
    echo "These files are generated by PlatformIO/ESP-IDF during the build process."
    echo "To fix this issue:"
    echo "1. Ensure the build completed successfully"
    echo "2. Check that 'pio run -e $ENV_NAME' completed without errors"
    echo "3. Verify the partition table is correctly specified in platformio.ini"
    exit 1
fi

echo ""
echo "✅ Firmware prepared successfully!"
echo "Files in $WOKWI_DIR:"
ls -lh "$WOKWI_DIR"/*.bin "$WOKWI_DIR"/*.elf 2>/dev/null || true
