#!/bin/bash
# Script to prepare firmware for Wokwi testing
# This creates a combined firmware image with bootloader, partitions, and app

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WOKWI_DIR="$PROJECT_ROOT/test/wokwi"

# Check if environment is specified
if [ -z "$1" ]; then
    echo "Usage: $0 <environment>"
    echo "Example: $0 esp32_V4_wokwi_debug"
    exit 1
fi

ENV_NAME=$1
BUILD_DIR="$PROJECT_ROOT/.pio/build/$ENV_NAME"
FIRMWARE_BIN="$BUILD_DIR/firmware.bin"
FIRMWARE_ELF="$BUILD_DIR/firmware.elf"

# PlatformIO stores bootloader and partitions in the build directory
# but they might be in subdirectories depending on the platform version
BOOTLOADER_BIN="$BUILD_DIR/bootloader.bin"
PARTITIONS_BIN="$BUILD_DIR/partitions.bin"

# Alternative locations for bootloader (ESP-IDF v4+ might use different paths)
if [ ! -f "$BOOTLOADER_BIN" ]; then
    ALT_BOOTLOADER="$BUILD_DIR/bootloader/bootloader.bin"
    if [ -f "$ALT_BOOTLOADER" ]; then
        BOOTLOADER_BIN="$ALT_BOOTLOADER"
    fi
fi

# Check if required files exist
MISSING_FILES=""

if [ ! -f "$FIRMWARE_BIN" ]; then
    echo "❌ ERROR: Firmware binary not found at $FIRMWARE_BIN"
    MISSING_FILES="${MISSING_FILES}firmware.bin "
fi

if [ ! -f "$BOOTLOADER_BIN" ]; then
    echo "❌ ERROR: bootloader.bin not found!"
    echo "   Checked: $BUILD_DIR/bootloader.bin"
    echo "   Also checked: $BUILD_DIR/bootloader/bootloader.bin"
    MISSING_FILES="${MISSING_FILES}bootloader.bin "
fi

if [ ! -f "$PARTITIONS_BIN" ]; then
    echo "❌ ERROR: partitions.bin not found at $PARTITIONS_BIN"
    MISSING_FILES="${MISSING_FILES}partitions.bin "
fi

if [ -n "$MISSING_FILES" ]; then
    echo ""
    echo "❌ ERROR: Missing required files: $MISSING_FILES"
    echo ""
    echo "Build directory contents:"
    ls -la "$BUILD_DIR" | head -20
    echo ""
    echo "These files are generated by PlatformIO/ESP-IDF during the build process."
    echo "To fix this issue:"
    echo "1. Ensure the build completed successfully: pio run -e $ENV_NAME"
    echo "2. Verify the partition table is correctly specified in platformio.ini"
    exit 1
fi

echo "Creating combined firmware image for Wokwi..."
echo "Using files from $ENV_NAME build:"
echo "  - Bootloader: $(basename $(dirname "$BOOTLOADER_BIN"))/$(basename "$BOOTLOADER_BIN")"
echo "  - Partitions: $PARTITIONS_BIN"
echo "  - Firmware:   $FIRMWARE_BIN"

# Create combined firmware image using esptool.py
# Standard ESP32 flash layout:
#   0x1000 - bootloader
#   0x8000 - partition table
#   0x10000 - application
echo ""
echo "Merging firmware components into combined image..."

# Check if esptool.py is available
if ! command -v esptool.py &> /dev/null; then
    echo "❌ ERROR: esptool.py not found"
    echo "Installing esptool..."
    pip install esptool || {
        echo "❌ ERROR: Failed to install esptool"
        echo "Please install manually: pip install esptool"
        exit 1
    }
fi

# Merge binaries into a single combined image
# This is the recommended approach for Wokwi to ensure proper filesystem support
esptool.py --chip esp32 merge_bin \
    -o "$WOKWI_DIR/firmware-combined.bin" \
    --flash_mode dio \
    --flash_freq 40m \
    --flash_size 4MB \
    0x1000 "$BOOTLOADER_BIN" \
    0x8000 "$PARTITIONS_BIN" \
    0x10000 "$FIRMWARE_BIN"

echo "✓ Created combined firmware image: firmware-combined.bin"

# Also copy ELF file for debugging
if [ -f "$FIRMWARE_ELF" ]; then
    cp "$FIRMWARE_ELF" "$WOKWI_DIR/firmware.elf"
    echo "✓ Copied firmware.elf for debugging"
else
    echo "⚠ Warning: firmware.elf not found"
fi

# Display combined image information
echo ""
echo "Combined firmware image details:"
ls -lh "$WOKWI_DIR/firmware-combined.bin"
echo ""
echo "Image structure:"
echo "  0x00001000 - Bootloader ($(stat -f%z "$BOOTLOADER_BIN" 2>/dev/null || stat -c%s "$BOOTLOADER_BIN") bytes)"
echo "  0x00008000 - Partition table ($(stat -f%z "$PARTITIONS_BIN" 2>/dev/null || stat -c%s "$PARTITIONS_BIN") bytes)"
echo "  0x00010000 - Application ($(stat -f%z "$FIRMWARE_BIN" 2>/dev/null || stat -c%s "$FIRMWARE_BIN") bytes)"

# Verify the combined image
echo ""
echo "Verifying combined image..."
python3 -c "
import sys
try:
    with open('$WOKWI_DIR/firmware-combined.bin', 'rb') as f:
        data = f.read()
    print(f'✓ Combined image size: {len(data)} bytes ({len(data)/1024/1024:.2f} MB)')
    
    # Check bootloader magic byte at offset 0x1000
    if len(data) > 0x1000 and data[0x1000] == 0xe9:
        print('✓ Bootloader magic byte (0xe9) found at 0x1000')
    else:
        print('⚠ Warning: Bootloader magic byte not found at expected location')
    
    # Check partition table magic bytes at offset 0x8000
    if len(data) > 0x8000 and data[0x8000:0x8002] == b'\xaa\x50':
        print('✓ Partition table magic bytes found at 0x8000')
    else:
        print('⚠ Warning: Partition table magic bytes not found at expected location')
    
    # Check application magic byte at offset 0x10000
    if len(data) > 0x10000 and data[0x10000] == 0xe9:
        print('✓ Application magic byte (0xe9) found at 0x10000')
    else:
        print('⚠ Warning: Application magic byte not found at expected location')
        
except Exception as e:
    print(f'❌ ERROR verifying image: {e}')
    sys.exit(1)
"

echo ""
echo "✅ Firmware prepared successfully!"
echo "Combined firmware image ready for Wokwi simulation."
